### ISSUE TITLE
have you seen project lisa? 

### ISSUE THREAD

**Issue by samuelstroschein** [Mirror-Labs/MirrorDB#1]
hi @funrep and @honungsburk, 

1. @honungsburk your website,linkedin,github has no email. hard to contact you 
2. @funrep the email on your website is outdated
3. are you both (?) interested in https://github.com/inlang/inlang/blob/main/open-positions/project-lisa.md?
 
the of mirrordb and project lisa seem similar. project lisa goes even further though. 

contact me at samuel.stroschein@inlang.com

**Comment by honungsburk** [comment]
Thanks for reaching out! Your link returns a 404, do you have another link? :)

**Comment by samuelstroschein** [comment]
wups. there you go https://github.com/inlang/inlang/blob/main/careers/project-lisa.md

**Comment by honungsburk** [comment]
Thanks, I'll take a look at it. What would be the best way of reaching out to you if I have any questions?

**Comment by samuelstroschein** [comment]
@honungsburk my email [samuel.stroschein@inlang.com](mailto:samuel.stroschein@inlang.com)

**Comment by honungsburk** [comment]
Thanks
